INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('68a051d7-6d82-4879-b0a3-1340e14db54d', 'Free internship', '2021-07-21T00:00', '2021-09-21T00:00', '2021-07-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 300, '2021-07-01T00:00', '2021-07-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('55fdfdd2-cac7-4851-a0a6-ba93113e926b', 'Free internship', '2021-08-21T00:00', '2021-10-21T00:00', '2021-08-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 200, '2021-08-01T00:00', '2021-10-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('0137afd2-42ca-49e4-9018-3499199fdf43', 'Free internship', '2021-07-21T00:00', '2021-09-21T00:00', '2021-07-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 150, '2021-07-01T00:00', '2021-07-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('967fdef2-18cd-4e77-aef0-7c831cd8263d', 'Free internship', '2021-08-21T00:00', '2021-10-21T00:00', '2021-08-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 100, '2021-08-01T00:00', '2021-10-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('1069033e-e317-407f-be0a-3adc99ae844c', 'Free internship', '2021-07-21T00:00', '2021-09-21T00:00', '2021-07-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 50, '2021-07-01T00:00', '2021-07-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('89b7a3ef-8561-41ca-a9ff-14415d3dc80c', 'Free internship', '2021-08-21T00:00', '2021-10-21T00:00', '2021-08-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 200, '2021-08-01T00:00', '2021-10-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('e0620a56-897a-4616-95e8-5ed1d5314974', 'Free internship', '2021-07-21T00:00', '2021-09-21T00:00', '2021-07-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 100, '2021-07-01T00:00', '2021-07-01T00:00', 'ONLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('7e571523-0c53-41b2-9b4d-2811bba896a2', 'Free internship', '2021-08-21T00:00', '2021-10-21T00:00', '2021-08-01T00:00', 'Docker; GitHub; Swagger UI', 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 50, '2021-08-01T00:00', '2021-10-01T00:00', 'OFFLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('8c888fc7-d126-4fe1-8023-b6071b7c7843', 'Free internship', '2021-07-21T00:00', '2021-09-21T00:00', '2021-07-01T00:00', 'Docker; GitHub; Swagger UI', 'На тренинге вы научитесь писать простой и «чистый» код, создавать программы, работающие в веб-браузере и имеющие веб-службы, разрабатывать приложения на стороне серверов для форумов, интернет-магазинов или опросов, а также создавать многофункциональные приложения', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 300, '2021-07-01T00:00', '2021-07-01T00:00', 'OFFLINE') ON CONFLICT (inship_id) DO NOTHING;
INSERT INTO internship (inship_id, inship_name, inship_start_date, inship_end_date, inship_publication_date, inship_tech_skills, inship_description, inship_requirements, inship_capacity, inship_registration_start_date, inship_registration_end_date, inship_format_name)
VALUES ('c48bf69e-f3a9-4ff0-a94a-f2a7f49a42dd', 'Free internship', '2021-08-21T00:00', '2021-10-21T00:00', '2021-08-01T00:00', 'Docker; GitHub; Swagger UI', 'На тренинге вы научитесь писать простой и «чистый» код; создавать программы, работающие в веб-браузере и имеющие веб-службы; разрабатывать приложения на стороне серверов для форумов, интернет-магазинов или опросов, а также создавать многофункциональные приложения', 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;', 200, '2021-08-01T00:00', '2021-10-01T00:00', 'OFFLINE') ON CONFLICT (inship_id) DO NOTHING;
