UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '68a051d7-6d82-4879-b0a3-1340e14db54d'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '55fdfdd2-cac7-4851-a0a6-ba93113e926b'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '0137afd2-42ca-49e4-9018-3499199fdf43'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '967fdef2-18cd-4e77-aef0-7c831cd8263d'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '1069033e-e317-407f-be0a-3adc99ae844c'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '89b7a3ef-8561-41ca-a9ff-14415d3dc80c'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = 'e0620a56-897a-4616-95e8-5ed1d5314974'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '7e571523-0c53-41b2-9b4d-2811bba896a2'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = '8c888fc7-d126-4fe1-8023-b6071b7c7843'
UPDATE internship SET inship_name = 'Free internship',inship_tech_skills = 'Docker; GitHub; Swagger UI', inship_description = 'During the training, you will learn how to write simple and "clean" code, create programs that run in a web browser and have web services, develop server-side applications for forums, online stores or surveys, and create multifunctional applications', inship_requirements = 'OOP knowledge: classes, encapsulation, polymorphism, inheritance;
knowledge of the basics of SQL and the basics of database design is desirable;
knowledge of English at a level not lower than A2;' WHERE inship_id = 'c48bf69e-f3a9-4ff0-a94a-f2a7f49a42dd'